/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>


using namespace cv;
using namespace std;
/* Header for class com_example_feez_feeopencv1_OpencvNativeClass */

#ifndef _Included_com_example_feez_feeopencv1_OpencvNativeClass
#define _Included_com_example_feez_feeopencv1_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_feez_feeopencv1_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img,Mat& gray);

JNIEXPORT jint JNICALL Java_com_example_feez_feeopencv1_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
